sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
services:
  - redis-server
install: true
script:
  - 'mvn package -U -Dmaven.test.redirectTestOutputToFile=false'
